# Generated by Django 3.1.4 on 2023-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo_empreendimento', models.CharField(choices=[('predio', 'Prédio'), ('loteamento', 'Loteamento')], default='predio', max_length=20)),
            ],
        ),
    ]
