# Generated by Django 3.1.4 on 2023-10-05 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0002_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empreendimentos.empreendimento'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_expiracao', models.DateTimeField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.unidade')),
            ],
        ),
    ]
