# Generated by Django 3.1.4 on 2023-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0004_auto_20231017_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='descricao',
            field=models.TextField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservar'), ('vendida', 'Vender')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
