# Generated by Django 3.1.4 on 2023-11-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0005_auto_20231127_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='preco',
            field=models.CharField(max_length=15),
        ),
    ]
