# Generated by Django 4.2.7 on 2023-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0010_alter_empreendimento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='material_divulgacao',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Material de Divulgação'),
        ),
    ]
