# Generated by Django 4.2.7 on 2023-12-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0011_empreendimento_material_divulgacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
