# Generated by Django 4.2.7 on 2023-12-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0014_unidade_data_hora_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='data_hora_reserva',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
